-- Seed all 100 activities from:
-- https://www.instructables.com/100-STEAM-Projects-for-Educators/
-- Run this after `supabase/steamh_projects_patch.sql`

with source_titles (idx, title, activity_url, cover_url) as (
  values
    (1, 'Sponge Motorboat', 'https://www.instructables.com/Sponge-Motorboat/', 'https://content.instructables.com/FNV/P7C0/IRW240GR/FNVP7C0IRW240GR.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (2, 'PVC Saxophone!', 'https://www.instructables.com/PVC-Saxophone-1/', 'https://content.instructables.com/FAX/1327/IRW2403Y/FAX1327IRW2403Y.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (3, 'Splitting Water the Easy Way', 'https://www.instructables.com/Splitting-Water-the-Easy-Way/', 'https://content.instructables.com/FN7/J1OU/IRW23ZGZ/FN7J1OUIRW23ZGZ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (4, 'Bag Monsters', 'https://www.instructables.com/Bag-Monsters/', 'https://content.instructables.com/F5L/YXM1/IRVVMFOC/F5LYXM1IRVVMFOC.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (5, 'Silly String Remote', 'https://www.instructables.com/Silly-String-Remote/', 'https://content.instructables.com/FYO/V4QC/IP5VWKOI/FYOV4QCIP5VWKOI.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (6, 'Writing Secret Messages in Color', 'https://www.instructables.com/Writing-Secret-Messages-in-Color/', 'https://content.instructables.com/FOO/2XM7/IKSN3ZMW/FOO2XM7IKSN3ZMW.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (7, 'Float Racers', 'https://www.instructables.com/Float-Racers/', 'https://content.instructables.com/FCS/N0PT/IKSN3Q8M/FCSN0PTIKSN3Q8M.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (8, 'Siphon Chain Reaction', 'https://www.instructables.com/Siphon-Chain-Reaction-1/', 'https://content.instructables.com/FGV/D2XR/IKSN3H1D/FGVD2XRIKSN3H1D.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (9, 'Magnet Trampoline', 'https://www.instructables.com/Magnet-Trampoline/', 'https://content.instructables.com/FR5/MSI3/IKSN3932/FR5MSI3IKSN3932.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (10, 'Magnet Building Sticks', 'https://www.instructables.com/Magnet-Building-Sticks/', 'https://content.instructables.com/FS2/ZSLN/IJWUV4L5/FS2ZSLNIJWUV4L5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (11, 'Mini Wave Model', 'https://www.instructables.com/Mini-Wave-Model-1/', 'https://content.instructables.com/FN3/XVG2/IJWUUVVU/FN3XVG2IJWUUVVU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (12, 'Motor Makeover', 'https://www.instructables.com/Motor-Makeover/', 'https://content.instructables.com/FCW/GBFQ/IJWUUEF9/FCWGBFQIJWUUEF9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (13, 'Glitter Rockets!', 'https://www.instructables.com/Glitter-Rockets/', 'https://content.instructables.com/FO1/AMPA/IKSN44U1/FO1AMPAIKSN44U1.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (14, 'Giant Sprinkler', 'https://www.instructables.com/Giant-Sprinkler/', 'https://content.instructables.com/F29/KQSE/IJWUUNB3/F29KQSEIJWUUNB3.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (15, 'Chicken Foot Dissection', 'https://www.instructables.com/Chicken-Foot-Dissection/', 'https://content.instructables.com/F4Y/449K/IRW23ZUK/F4Y449KIRW23ZUK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (16, 'Balloon Trombone', 'https://www.instructables.com/Balloon-Trombone/', 'https://content.instructables.com/FUP/513O/IKSN4DN3/FUP513OIKSN4DN3.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (17, 'Universal Bluetooth', 'https://www.instructables.com/Universal-Bluetooth/', 'https://content.instructables.com/FOZ/GHYQ/IJQOMM7P/FOZGHYQIJQOMM7P.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (18, 'Hand Pump!', 'https://www.instructables.com/Hand-Pump/', 'https://content.instructables.com/FGS/UGN0/IJQOMAT4/FGSUGN0IJQOMAT4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (19, 'The Rocking Dish', 'https://www.instructables.com/The-Unbalanced-Dish/', 'https://content.instructables.com/FGY/WAPW/IJWUV65D/FGYWAPWIJWUV65D.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (20, 'Making Color Mash-Ups', 'https://www.instructables.com/Making-Color-Mash-Ups/', 'https://content.instructables.com/FB5/DAUC/IJQOLYX6/FB5DAUCIJQOLYX6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (21, 'Candle Experiments and Explorations', 'https://www.instructables.com/Candle-Experiments-and-Explorations/', 'https://content.instructables.com/FB6/1139/IJUCO3NY/FB61139IJUCO3NY.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (22, 'Shake Generator', 'https://www.instructables.com/Shake-Generator/', 'https://content.instructables.com/F96/9V56/IJUCLGCL/F969V56IJUCLGCL.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (23, 'Vacuum Buzzer', 'https://www.instructables.com/No-Sound-in-Space-the-Handheld-Version/', 'https://content.instructables.com/FAW/PLKN/IJUCL1SU/FAWPLKNIJUCL1SU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (24, 'Everchanging Ball Maze', 'https://www.instructables.com/Everchanging-Ball-Maze/', 'https://content.instructables.com/FEO/R9SB/IJUCIA8E/FEOR9SBIJUCIA8E.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (25, 'Heart Dissection', 'https://www.instructables.com/Heart-Dissection/', 'https://content.instructables.com/F33/TQL1/IJUCHB6N/F33TQL1IJUCHB6N.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (26, 'The Most Marvelous Honk', 'https://www.instructables.com/The-Most-Marvelous-Honk/', 'https://content.instructables.com/FA6/JCAM/IJQOEFY5/FA6JCAMIJQOEFY5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (27, 'Dream Island Mapping Project', 'https://www.instructables.com/Dream-Island-Mapping-Project/', 'https://content.instructables.com/FYK/KBPA/IJQOE8QM/FYKKBPAIJQOE8QM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (28, 'Holiday Card Pigment Puzzle', 'https://www.instructables.com/CMYK-Holiday-Card-Puzzle/', 'https://content.instructables.com/F0S/Y9GL/IIAOKTGP/F0SY9GLIIAOKTGP.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (29, 'Rock Tests 101', 'https://www.instructables.com/Rock-Tests-101/', 'https://content.instructables.com/F6J/SI0G/II8ZW1KK/F6JSI0GII8ZW1KK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (30, 'Night Kaleidoscope', 'https://www.instructables.com/Night-Kaleidoscope/', 'https://content.instructables.com/FJW/UZ0K/II0K55L9/FJWUZ0KII0K55L9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (31, 'Tiny Slide Shows!  (by Hacking Toy Cameras)', 'https://www.instructables.com/Micro-Photo-Albums-by-Hacking-Toy-Cameras/', 'https://content.instructables.com/F8O/7XSK/II0K4R6I/F8O7XSKII0K4R6I.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (32, 'Self-Defeating Fan Car', 'https://www.instructables.com/Self-Defeating-Fan-Car/', 'https://content.instructables.com/FX1/PUWZ/IHXB6H5E/FX1PUWZIHXB6H5E.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (33, 'Oil and Ice Density Experiment', 'https://www.instructables.com/Oil-and-Ice-Density-Experiment/', 'https://content.instructables.com/F38/A07A/IHWBXLRX/F38A07AIHWBXLRX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (34, 'Glowstick Dissection and Painting', 'https://www.instructables.com/Glowstick-Dissection-and-Painting/', 'https://content.instructables.com/FXF/XSBL/IHRZG87G/FXFXSBLIHRZG87G.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (35, 'Wood Arch Blocks in 5 Minutes!', 'https://www.instructables.com/Wood-Arches-in-5-Minutes/', 'https://content.instructables.com/FGV/2EMK/IHQK0ZES/FGV2EMKIHQK0ZES.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (36, 'Learning About Motion With Light Painting', 'https://www.instructables.com/Learning-about-Motion-with-Lightpainting/', 'https://content.instructables.com/FWS/3XRB/IGCJM4SO/FWS3XRBIGCJM4SO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (37, 'Lobster Dissection', 'https://www.instructables.com/Lobster-Dissection/', 'https://content.instructables.com/FIW/VY8X/IGB47J5T/FIWVY8XIGB47J5T.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (38, 'Bike Wheel Gyroscope', 'https://www.instructables.com/Bike-Wheel-Gyroscope/', 'https://content.instructables.com/FM5/46T6/IG3WTYXS/FM546T6IG3WTYXS.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (39, 'Reverse Trick-Or-Treating', 'https://www.instructables.com/Reverse-Trick-Or-Treating/', 'https://content.instructables.com/FUO/SOZE/IFZOMMF8/FUOSOZEIFZOMMF8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (40, 'A Foot in the Door', 'https://www.instructables.com/A-Foot-In-The-Door/', 'https://content.instructables.com/FOU/IPEE/IFY99EXZ/FOUIPEEIFY99EXZ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (41, 'Zombie Soda', 'https://www.instructables.com/Zombie-Soda/', 'https://content.instructables.com/F2X/Z7IK/IFTYVUKD/F2XZ7IKIFTYVUKD.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (42, 'Liquid Hourglass', 'https://www.instructables.com/Liquid-Hourglass/', 'https://content.instructables.com/F6H/22RE/IFPMFW8F/F6H22REIFPMFW8F.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (43, 'The Most Annoying Sound in the World', 'https://www.instructables.com/The-Most-Annoying-Sound-in-the-World/', 'https://content.instructables.com/FRC/WEYP/IFMRO2ND/FRCWEYPIFMRO2ND.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (44, 'Water Balloon Slingshot (in 3 Minutes)', 'https://www.instructables.com/Water-Balloon-Slingshot-in-3-minutes/', 'https://content.instructables.com/FJH/0XW0/IFJWN8G7/FJH0XW0IFJWN8G7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (45, 'Helping Hands', 'https://www.instructables.com/Helping-Hands-2/', 'https://content.instructables.com/F60/W4FG/IFISEFO6/F60W4FGIFISEFO6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (46, 'Balancing Bottle Trees!', 'https://www.instructables.com/Balancing-Bottle-Trees/', 'https://content.instructables.com/FF8/1QOO/IFF8EHFS/FF81QOOIFF8EHFS.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (47, 'Water Drop Science: 8 Explorations', 'https://www.instructables.com/Water-Drop-Science-8-Explorations/', 'https://content.instructables.com/FVT/UYYR/IEN4QZEK/FVTUYYRIEN4QZEK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (48, 'Infinite Worlds Viewer!', 'https://www.instructables.com/Infinite-World-Viewer/', 'https://content.instructables.com/F1S/8P5O/IEKJ1K52/F1S8P5OIEKJ1K52.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (49, 'Bubble Window!', 'https://www.instructables.com/Bubble-Window/', 'https://content.instructables.com/F5C/NC5Q/IDUQS2HX/F5CNC5QIDUQS2HX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (50, 'Side-Bending Goggles', 'https://www.instructables.com/Side-Bending-Goggles/', 'https://content.instructables.com/FSS/2R7C/IDTAW633/FSS2R7CIDTAW633.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (51, 'Lava Boogers! (aka Waxy Earth Science)', 'https://www.instructables.com/Lava-Boogers-waxy-Earth-Science/', 'https://content.instructables.com/FV8/2XGZ/ICPP7VFA/FV82XGZICPP7VFA.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (52, 'Homemade Fossils!', 'https://www.instructables.com/Homemade-Fossils/', 'https://content.instructables.com/FYW/U24D/ICN7GA9I/FYWU24DICN7GA9I.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (53, 'Emergency DiscOveralls (in 30 Minutes!)', 'https://www.instructables.com/Emergency-DiscOveralls-in-30-minutes/', 'https://content.instructables.com/FHR/BCE3/ICG2DKP4/FHRBCE3ICG2DKP4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (54, 'Brainstorm Mobile', 'https://www.instructables.com/Brainstorm-Mobile/', 'https://content.instructables.com/F7Z/Q003/IFF8FGXD/F7ZQ003IFF8FGXD.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (55, 'Tooth Phonograph!', 'https://www.instructables.com/Tooth-Phonograph/', 'https://content.instructables.com/FJ0/DKI0/IC7HMHIJ/FJ0DKI0IC7HMHIJ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (56, 'Grow Seeds Without Soil!', 'https://www.instructables.com/Start-Seeds-Without-Soil/', 'https://content.instructables.com/FLG/AC6U/IC7HM8P7/FLGAC6UIC7HM8P7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (57, 'Sound Flipping Headphones!', 'https://www.instructables.com/Sound-Flipping-Headphones/', 'https://content.instructables.com/FIA/I0DL/IC7HLWB9/FIAI0DLIC7HLWB9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (58, 'Homemade Harmonograph!', 'https://www.instructables.com/Homemade-Harmonograph/', 'https://content.instructables.com/FR6/VGF9/IBXMNFTK/FR6VGF9IBXMNFTK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (59, 'Instant Clouds: Just Add Pressure!', 'https://www.instructables.com/Instant-Cloud-Just-Add-Pressure/', 'https://content.instructables.com/FV3/8QK2/IBC22EA6/FV38QK2IBC22EA6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (60, 'Grow Bacteria From Gross Stuff!', 'https://www.instructables.com/Growing-Bacteria-From-Gross-Stuff/', 'https://content.instructables.com/F5E/Y64A/IBAMPM1L/F5EY64AIBAMPM1L.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (61, 'Self-Watering Terrarium!', 'https://www.instructables.com/Self-Watering-Terrarium/', 'https://content.instructables.com/F66/FNV8/IB8J02L7/F66FNV8IB8J02L7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (62, 'Bike Wheel Wave Machine!', 'https://www.instructables.com/Bike-Wheel-Wave-Machine/', 'https://content.instructables.com/FPQ/43IY/IB49M7IX/FPQ43IYIB49M7IX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (63, 'Water Bottle Pressure Prank! (pranked by Science)', 'https://www.instructables.com/Water-Bottle-Pressure-Prank-pranked-by-science/', 'https://content.instructables.com/FZT/58J3/IATHEU21/FZT58J3IATHEU21.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (64, 'Fish Dissection!', 'https://www.instructables.com/Fish-Dissection/', 'https://content.instructables.com/FG6/YTS3/IATHBM0A/FG6YTS3IATHBM0A.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (65, 'Instant Pickles! (30 Second Vacuum Pickles!)', 'https://www.instructables.com/Instant-Pickles-30-second-vacuum-pickles/', 'https://content.instructables.com/F28/FL1G/IAS1ZEDO/F28FL1GIAS1ZEDO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (66, 'Craft Stick Catapult!', 'https://www.instructables.com/Craft-Stick-Catapult/', 'https://content.instructables.com/FUA/4DSJ/IAP73BWK/FUA4DSJIAP73BWK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (67, '5 Toys That Spin!', 'https://www.instructables.com/5-Quick-Spinning-Toys/', 'https://content.instructables.com/FSD/MSMI/IAJNXH64/FSDMSMIIAJNXH64.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (68, 'Cardboard Fortress Battle! (capture the Flag)', 'https://www.instructables.com/Cardboard-Fortress-Battle-capture-the-flag/', 'https://content.instructables.com/F0Z/SXWO/I9YC14KO/F0ZSXWOI9YC14KO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (69, 'Bottle Boogie Flute!', 'https://www.instructables.com/Bottle-Boogie-Flute/', 'https://content.instructables.com/F7P/R4U0/I9YBIT0H/F7PR4U0I9YBIT0H.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (70, 'Galaxy Scanner!  (make Planetary Pictures at Home)', 'https://www.instructables.com/Galaxy-Scanner-make-planetary-pictures-at-home/', 'https://content.instructables.com/F5O/ZE0H/I9UEA1WU/F5OZE0HI9UEA1WU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (71, 'Viscosity Tube Tumbler', 'https://www.instructables.com/Viscosity-Tube-Tumbler/', 'https://content.instructables.com/FY8/3WBR/I9LZH6TG/FY83WBRI9LZH6TG.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (72, 'Wind Tube!', 'https://www.instructables.com/Wind-Tube/', 'https://content.instructables.com/FQL/XIXK/I9JR90BI/FQLXIXKI9JR90BI.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (73, 'Glitter Roulette With Party Poppers', 'https://www.instructables.com/Glitter-Roulette-with-Party-Poppers/', 'https://content.instructables.com/FDV/6MDR/I9E1C8UW/FDV6MDRI9E1C8UW.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (74, 'Water Lava Lamp (learning Density)', 'https://www.instructables.com/Water-Lava-Lamp/', 'https://content.instructables.com/FP1/I98W/I9CLWFHM/FP1I98WI9CLWFHM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (75, 'PVC Speaker From Scratch!', 'https://www.instructables.com/PVC-Speaker-From-Scratch/', 'https://content.instructables.com/FV1/FBFZ/I9C84J63/FV1FBFZI9C84J63.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (76, 'Maggie the Simple Electromagnet!', 'https://www.instructables.com/Maggie-the-Electromagnet/', 'https://content.instructables.com/FQK/O9GZ/I9B6HD0U/FQKO9GZI9B6HD0U.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (77, 'Make a Muppet Puppet!', 'https://www.instructables.com/Make-a-Muppet-Puppet/', 'https://content.instructables.com/FGG/KXKL/I9ABB0CW/FGGKXKLI9ABB0CW.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (78, 'Water Drop Trampoline', 'https://www.instructables.com/Water-Drop-Trampoline/', 'https://content.instructables.com/FVZ/JQSS/I95GQQS8/FVZJQSSI95GQQS8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (79, 'Music You Can See', 'https://www.instructables.com/Music-You-Can-See/', 'https://content.instructables.com/F8G/JGJ4/I95GPBWC/F8GJGJ4I95GPBWC.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (80, 'Wind Turbine Game!', 'https://www.instructables.com/Wind-Turbine-Game/', 'https://content.instructables.com/FZH/IRXF/I92LTXSM/FZHIRXFI92LTXSM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (81, 'Flower Dissection!', 'https://www.instructables.com/Flower-Dissection/', 'https://content.instructables.com/FAV/7R4G/I916FKAL/FAV7R4GI916FKAL.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (82, 'Wire Maze!', 'https://www.instructables.com/Wire-Maze/', 'https://content.instructables.com/F4F/V1YF/I8YBOJHB/F4FV1YFI8YBOJHB.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (83, 'Pinhole Eye Model', 'https://www.instructables.com/Pinhole-Eye-Model/', 'https://content.instructables.com/F0V/D219/I8UUVBMU/F0VD219I8UUVBMU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (84, 'Light Drum!', 'https://www.instructables.com/Light-Drum/', 'https://content.instructables.com/FW6/ZHC9/I8UUV7U5/FW6ZHC9I8UUV7U5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (85, 'Squid Dissection', 'https://www.instructables.com/Squid-Dissection/', 'https://content.instructables.com/FEU/I2IK/I8PQWTJH/FEUI2IKI8PQWTJH.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (86, 'Rubber Band Harmonica!', 'https://www.instructables.com/Rubber-Band-Harmonica/', 'https://content.instructables.com/FH8/NMX6/I8PQVS2B/FH8NMX6I8PQVS2B.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (87, 'Glove-a-Trombone!', 'https://www.instructables.com/Glove-a-Trombone/', 'https://content.instructables.com/FJ1/W7YA/I8MVZ3NL/FJ1W7YAI8MVZ3NL.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (88, 'Giant Wave Model!', 'https://www.instructables.com/Giant-Wave-Model/', 'https://content.instructables.com/F20/37DP/IGCJLUNF/F2037DPIGCJLUNF.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (89, 'Circuit Tiles!', 'https://www.instructables.com/Circuit-Tiles/', 'https://content.instructables.com/FCI/WTYJ/I8K13MM4/FCIWTYJI8K13MM4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (90, 'Jurassic Pie!', 'https://www.instructables.com/Jurassic-Pie-aka-Volcano-Cake/', 'https://content.instructables.com/FJE/R74V/I8H69CK1/FJER74VI8H69CK1.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (91, 'Strobe Goggles: Your Ticket to Stardom!', 'https://www.instructables.com/Strobe-Goggles/', 'https://content.instructables.com/FRU/I248/I8FQRERX/FRUI248I8FQRERX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (92, 'Elasti-Bot: the Posable Wooden Robot', 'https://www.instructables.com/Elasti-Bot-the-posable-wooden-robot/', 'https://content.instructables.com/FQZ/JC80/I8BGGZFI/FQZJC80I8BGGZFI.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (93, 'Balance Bot Buddy!', 'https://www.instructables.com/Build-a-Balancing-Bot-Buddy/', 'https://content.instructables.com/FTT/5SC2/I8BGHB11/FTT5SC2I8BGHB11.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (94, 'BoomBucket: the Boombox Bucket!', 'https://www.instructables.com/BoomBucket-the-boombox-bucket/', 'https://content.instructables.com/F1J/B78B/I3H52O7F/F1JB78BI3H52O7F.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (95, 'Scissor Lift (by Craft Sticks!)', 'https://www.instructables.com/Scissor-Lift-by-craft-sticks/', 'https://content.instructables.com/FKH/X4WQ/I3H52UP9/FKHX4WQI3H52UP9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (96, 'Straw Propellor', 'https://www.instructables.com/Straw-Propellor/', 'https://content.instructables.com/FSB/KYIO/I3BH745F/FSBKYIOI3BH745F.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (97, 'Bite-sized Boombox', 'https://www.instructables.com/BoomBiteBox-listening-with-your-teeth/', 'https://content.instructables.com/F3S/DJR3/I3AKC21M/F3SDJR3I3AKC21M.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (98, 'Wobble Bot!', 'https://www.instructables.com/Wobble-Bot/', 'https://content.instructables.com/FE6/5T8K/I3AKBGB8/FE65T8KI3AKBGB8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (99, 'Straw Finger', 'https://www.instructables.com/Straw-Finger/', 'https://content.instructables.com/FFI/P4IM/I395RYUI/FFIP4IMI395RYUI.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (100, 'Straw Flute', 'https://www.instructables.com/Straw-Flute/', 'https://content.instructables.com/F7Y/TM0F/I395RQCF/F7YTM0FI395RQCF.png?auto=webp&crop=1.2%3A1&frame=1&width=306')
)
insert into public.steamh_projects (
  student_id,
  student_name,
  school_name,
  grade,
  subject,
  title,
  summary,
  description,
  challenge,
  solution,
  tools_used,
  tags,
  image_urls,
  video_urls,
  attachment_urls,
  external_links,
  published,
  created_at,
  updated_at
)
select
  null as student_id,
  'The Oakland Toy Lab' as student_name,
  'Instructables Educator Collection' as school_name,
  '6-10' as grade,
  'STEAM Activity' as subject,
  source_titles.title,
  format('Classroom STEAM activity #%s from the Instructables educator collection.', source_titles.idx),
  format(
    'Curated from the "100 STEAM Projects for Educators" list on Instructables. Activity: %s',
    source_titles.title
  ),
  null as challenge,
  null as solution,
  '{}'::text[] as tools_used,
  array['instructables', 'steam', 'classroom']::text[] as tags,
  jsonb_build_array(source_titles.cover_url) as image_urls,
  '[]'::jsonb as video_urls,
  '[]'::jsonb as attachment_urls,
  jsonb_build_array(
    jsonb_build_object(
      'label', 'Activity Page',
      'url', source_titles.activity_url
    ),
    jsonb_build_object(
      'label', 'Source Collection',
      'url', 'https://www.instructables.com/100-STEAM-Projects-for-Educators/'
    )
  ) as external_links,
  true as published,
  now() - ((101 - source_titles.idx)::text || ' days')::interval as created_at,
  now() - ((101 - source_titles.idx)::text || ' days')::interval as updated_at
from source_titles
where not exists (
  select 1
  from public.steamh_projects existing
  where lower(existing.title) = lower(source_titles.title)
);

with source_titles (idx, title, activity_url, cover_url) as (
  values
    (1, 'Sponge Motorboat', 'https://www.instructables.com/Sponge-Motorboat/', 'https://content.instructables.com/FNV/P7C0/IRW240GR/FNVP7C0IRW240GR.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (2, 'PVC Saxophone!', 'https://www.instructables.com/PVC-Saxophone-1/', 'https://content.instructables.com/FAX/1327/IRW2403Y/FAX1327IRW2403Y.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (3, 'Splitting Water the Easy Way', 'https://www.instructables.com/Splitting-Water-the-Easy-Way/', 'https://content.instructables.com/FN7/J1OU/IRW23ZGZ/FN7J1OUIRW23ZGZ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (4, 'Bag Monsters', 'https://www.instructables.com/Bag-Monsters/', 'https://content.instructables.com/F5L/YXM1/IRVVMFOC/F5LYXM1IRVVMFOC.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (5, 'Silly String Remote', 'https://www.instructables.com/Silly-String-Remote/', 'https://content.instructables.com/FYO/V4QC/IP5VWKOI/FYOV4QCIP5VWKOI.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (6, 'Writing Secret Messages in Color', 'https://www.instructables.com/Writing-Secret-Messages-in-Color/', 'https://content.instructables.com/FOO/2XM7/IKSN3ZMW/FOO2XM7IKSN3ZMW.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (7, 'Float Racers', 'https://www.instructables.com/Float-Racers/', 'https://content.instructables.com/FCS/N0PT/IKSN3Q8M/FCSN0PTIKSN3Q8M.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (8, 'Siphon Chain Reaction', 'https://www.instructables.com/Siphon-Chain-Reaction-1/', 'https://content.instructables.com/FGV/D2XR/IKSN3H1D/FGVD2XRIKSN3H1D.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (9, 'Magnet Trampoline', 'https://www.instructables.com/Magnet-Trampoline/', 'https://content.instructables.com/FR5/MSI3/IKSN3932/FR5MSI3IKSN3932.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (10, 'Magnet Building Sticks', 'https://www.instructables.com/Magnet-Building-Sticks/', 'https://content.instructables.com/FS2/ZSLN/IJWUV4L5/FS2ZSLNIJWUV4L5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (11, 'Mini Wave Model', 'https://www.instructables.com/Mini-Wave-Model-1/', 'https://content.instructables.com/FN3/XVG2/IJWUUVVU/FN3XVG2IJWUUVVU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (12, 'Motor Makeover', 'https://www.instructables.com/Motor-Makeover/', 'https://content.instructables.com/FCW/GBFQ/IJWUUEF9/FCWGBFQIJWUUEF9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (13, 'Glitter Rockets!', 'https://www.instructables.com/Glitter-Rockets/', 'https://content.instructables.com/FO1/AMPA/IKSN44U1/FO1AMPAIKSN44U1.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (14, 'Giant Sprinkler', 'https://www.instructables.com/Giant-Sprinkler/', 'https://content.instructables.com/F29/KQSE/IJWUUNB3/F29KQSEIJWUUNB3.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (15, 'Chicken Foot Dissection', 'https://www.instructables.com/Chicken-Foot-Dissection/', 'https://content.instructables.com/F4Y/449K/IRW23ZUK/F4Y449KIRW23ZUK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (16, 'Balloon Trombone', 'https://www.instructables.com/Balloon-Trombone/', 'https://content.instructables.com/FUP/513O/IKSN4DN3/FUP513OIKSN4DN3.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (17, 'Universal Bluetooth', 'https://www.instructables.com/Universal-Bluetooth/', 'https://content.instructables.com/FOZ/GHYQ/IJQOMM7P/FOZGHYQIJQOMM7P.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (18, 'Hand Pump!', 'https://www.instructables.com/Hand-Pump/', 'https://content.instructables.com/FGS/UGN0/IJQOMAT4/FGSUGN0IJQOMAT4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (19, 'The Rocking Dish', 'https://www.instructables.com/The-Unbalanced-Dish/', 'https://content.instructables.com/FGY/WAPW/IJWUV65D/FGYWAPWIJWUV65D.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (20, 'Making Color Mash-Ups', 'https://www.instructables.com/Making-Color-Mash-Ups/', 'https://content.instructables.com/FB5/DAUC/IJQOLYX6/FB5DAUCIJQOLYX6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (21, 'Candle Experiments and Explorations', 'https://www.instructables.com/Candle-Experiments-and-Explorations/', 'https://content.instructables.com/FB6/1139/IJUCO3NY/FB61139IJUCO3NY.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (22, 'Shake Generator', 'https://www.instructables.com/Shake-Generator/', 'https://content.instructables.com/F96/9V56/IJUCLGCL/F969V56IJUCLGCL.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (23, 'Vacuum Buzzer', 'https://www.instructables.com/No-Sound-in-Space-the-Handheld-Version/', 'https://content.instructables.com/FAW/PLKN/IJUCL1SU/FAWPLKNIJUCL1SU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (24, 'Everchanging Ball Maze', 'https://www.instructables.com/Everchanging-Ball-Maze/', 'https://content.instructables.com/FEO/R9SB/IJUCIA8E/FEOR9SBIJUCIA8E.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (25, 'Heart Dissection', 'https://www.instructables.com/Heart-Dissection/', 'https://content.instructables.com/F33/TQL1/IJUCHB6N/F33TQL1IJUCHB6N.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (26, 'The Most Marvelous Honk', 'https://www.instructables.com/The-Most-Marvelous-Honk/', 'https://content.instructables.com/FA6/JCAM/IJQOEFY5/FA6JCAMIJQOEFY5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (27, 'Dream Island Mapping Project', 'https://www.instructables.com/Dream-Island-Mapping-Project/', 'https://content.instructables.com/FYK/KBPA/IJQOE8QM/FYKKBPAIJQOE8QM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (28, 'Holiday Card Pigment Puzzle', 'https://www.instructables.com/CMYK-Holiday-Card-Puzzle/', 'https://content.instructables.com/F0S/Y9GL/IIAOKTGP/F0SY9GLIIAOKTGP.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (29, 'Rock Tests 101', 'https://www.instructables.com/Rock-Tests-101/', 'https://content.instructables.com/F6J/SI0G/II8ZW1KK/F6JSI0GII8ZW1KK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (30, 'Night Kaleidoscope', 'https://www.instructables.com/Night-Kaleidoscope/', 'https://content.instructables.com/FJW/UZ0K/II0K55L9/FJWUZ0KII0K55L9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (31, 'Tiny Slide Shows!  (by Hacking Toy Cameras)', 'https://www.instructables.com/Micro-Photo-Albums-by-Hacking-Toy-Cameras/', 'https://content.instructables.com/F8O/7XSK/II0K4R6I/F8O7XSKII0K4R6I.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (32, 'Self-Defeating Fan Car', 'https://www.instructables.com/Self-Defeating-Fan-Car/', 'https://content.instructables.com/FX1/PUWZ/IHXB6H5E/FX1PUWZIHXB6H5E.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (33, 'Oil and Ice Density Experiment', 'https://www.instructables.com/Oil-and-Ice-Density-Experiment/', 'https://content.instructables.com/F38/A07A/IHWBXLRX/F38A07AIHWBXLRX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (34, 'Glowstick Dissection and Painting', 'https://www.instructables.com/Glowstick-Dissection-and-Painting/', 'https://content.instructables.com/FXF/XSBL/IHRZG87G/FXFXSBLIHRZG87G.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (35, 'Wood Arch Blocks in 5 Minutes!', 'https://www.instructables.com/Wood-Arches-in-5-Minutes/', 'https://content.instructables.com/FGV/2EMK/IHQK0ZES/FGV2EMKIHQK0ZES.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (36, 'Learning About Motion With Light Painting', 'https://www.instructables.com/Learning-about-Motion-with-Lightpainting/', 'https://content.instructables.com/FWS/3XRB/IGCJM4SO/FWS3XRBIGCJM4SO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (37, 'Lobster Dissection', 'https://www.instructables.com/Lobster-Dissection/', 'https://content.instructables.com/FIW/VY8X/IGB47J5T/FIWVY8XIGB47J5T.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (38, 'Bike Wheel Gyroscope', 'https://www.instructables.com/Bike-Wheel-Gyroscope/', 'https://content.instructables.com/FM5/46T6/IG3WTYXS/FM546T6IG3WTYXS.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (39, 'Reverse Trick-Or-Treating', 'https://www.instructables.com/Reverse-Trick-Or-Treating/', 'https://content.instructables.com/FUO/SOZE/IFZOMMF8/FUOSOZEIFZOMMF8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (40, 'A Foot in the Door', 'https://www.instructables.com/A-Foot-In-The-Door/', 'https://content.instructables.com/FOU/IPEE/IFY99EXZ/FOUIPEEIFY99EXZ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (41, 'Zombie Soda', 'https://www.instructables.com/Zombie-Soda/', 'https://content.instructables.com/F2X/Z7IK/IFTYVUKD/F2XZ7IKIFTYVUKD.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (42, 'Liquid Hourglass', 'https://www.instructables.com/Liquid-Hourglass/', 'https://content.instructables.com/F6H/22RE/IFPMFW8F/F6H22REIFPMFW8F.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (43, 'The Most Annoying Sound in the World', 'https://www.instructables.com/The-Most-Annoying-Sound-in-the-World/', 'https://content.instructables.com/FRC/WEYP/IFMRO2ND/FRCWEYPIFMRO2ND.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (44, 'Water Balloon Slingshot (in 3 Minutes)', 'https://www.instructables.com/Water-Balloon-Slingshot-in-3-minutes/', 'https://content.instructables.com/FJH/0XW0/IFJWN8G7/FJH0XW0IFJWN8G7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (45, 'Helping Hands', 'https://www.instructables.com/Helping-Hands-2/', 'https://content.instructables.com/F60/W4FG/IFISEFO6/F60W4FGIFISEFO6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (46, 'Balancing Bottle Trees!', 'https://www.instructables.com/Balancing-Bottle-Trees/', 'https://content.instructables.com/FF8/1QOO/IFF8EHFS/FF81QOOIFF8EHFS.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (47, 'Water Drop Science: 8 Explorations', 'https://www.instructables.com/Water-Drop-Science-8-Explorations/', 'https://content.instructables.com/FVT/UYYR/IEN4QZEK/FVTUYYRIEN4QZEK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (48, 'Infinite Worlds Viewer!', 'https://www.instructables.com/Infinite-World-Viewer/', 'https://content.instructables.com/F1S/8P5O/IEKJ1K52/F1S8P5OIEKJ1K52.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (49, 'Bubble Window!', 'https://www.instructables.com/Bubble-Window/', 'https://content.instructables.com/F5C/NC5Q/IDUQS2HX/F5CNC5QIDUQS2HX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (50, 'Side-Bending Goggles', 'https://www.instructables.com/Side-Bending-Goggles/', 'https://content.instructables.com/FSS/2R7C/IDTAW633/FSS2R7CIDTAW633.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (51, 'Lava Boogers! (aka Waxy Earth Science)', 'https://www.instructables.com/Lava-Boogers-waxy-Earth-Science/', 'https://content.instructables.com/FV8/2XGZ/ICPP7VFA/FV82XGZICPP7VFA.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (52, 'Homemade Fossils!', 'https://www.instructables.com/Homemade-Fossils/', 'https://content.instructables.com/FYW/U24D/ICN7GA9I/FYWU24DICN7GA9I.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (53, 'Emergency DiscOveralls (in 30 Minutes!)', 'https://www.instructables.com/Emergency-DiscOveralls-in-30-minutes/', 'https://content.instructables.com/FHR/BCE3/ICG2DKP4/FHRBCE3ICG2DKP4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (54, 'Brainstorm Mobile', 'https://www.instructables.com/Brainstorm-Mobile/', 'https://content.instructables.com/F7Z/Q003/IFF8FGXD/F7ZQ003IFF8FGXD.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (55, 'Tooth Phonograph!', 'https://www.instructables.com/Tooth-Phonograph/', 'https://content.instructables.com/FJ0/DKI0/IC7HMHIJ/FJ0DKI0IC7HMHIJ.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (56, 'Grow Seeds Without Soil!', 'https://www.instructables.com/Start-Seeds-Without-Soil/', 'https://content.instructables.com/FLG/AC6U/IC7HM8P7/FLGAC6UIC7HM8P7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (57, 'Sound Flipping Headphones!', 'https://www.instructables.com/Sound-Flipping-Headphones/', 'https://content.instructables.com/FIA/I0DL/IC7HLWB9/FIAI0DLIC7HLWB9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (58, 'Homemade Harmonograph!', 'https://www.instructables.com/Homemade-Harmonograph/', 'https://content.instructables.com/FR6/VGF9/IBXMNFTK/FR6VGF9IBXMNFTK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (59, 'Instant Clouds: Just Add Pressure!', 'https://www.instructables.com/Instant-Cloud-Just-Add-Pressure/', 'https://content.instructables.com/FV3/8QK2/IBC22EA6/FV38QK2IBC22EA6.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (60, 'Grow Bacteria From Gross Stuff!', 'https://www.instructables.com/Growing-Bacteria-From-Gross-Stuff/', 'https://content.instructables.com/F5E/Y64A/IBAMPM1L/F5EY64AIBAMPM1L.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (61, 'Self-Watering Terrarium!', 'https://www.instructables.com/Self-Watering-Terrarium/', 'https://content.instructables.com/F66/FNV8/IB8J02L7/F66FNV8IB8J02L7.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (62, 'Bike Wheel Wave Machine!', 'https://www.instructables.com/Bike-Wheel-Wave-Machine/', 'https://content.instructables.com/FPQ/43IY/IB49M7IX/FPQ43IYIB49M7IX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (63, 'Water Bottle Pressure Prank! (pranked by Science)', 'https://www.instructables.com/Water-Bottle-Pressure-Prank-pranked-by-science/', 'https://content.instructables.com/FZT/58J3/IATHEU21/FZT58J3IATHEU21.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (64, 'Fish Dissection!', 'https://www.instructables.com/Fish-Dissection/', 'https://content.instructables.com/FG6/YTS3/IATHBM0A/FG6YTS3IATHBM0A.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (65, 'Instant Pickles! (30 Second Vacuum Pickles!)', 'https://www.instructables.com/Instant-Pickles-30-second-vacuum-pickles/', 'https://content.instructables.com/F28/FL1G/IAS1ZEDO/F28FL1GIAS1ZEDO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (66, 'Craft Stick Catapult!', 'https://www.instructables.com/Craft-Stick-Catapult/', 'https://content.instructables.com/FUA/4DSJ/IAP73BWK/FUA4DSJIAP73BWK.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (67, '5 Toys That Spin!', 'https://www.instructables.com/5-Quick-Spinning-Toys/', 'https://content.instructables.com/FSD/MSMI/IAJNXH64/FSDMSMIIAJNXH64.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (68, 'Cardboard Fortress Battle! (capture the Flag)', 'https://www.instructables.com/Cardboard-Fortress-Battle-capture-the-flag/', 'https://content.instructables.com/F0Z/SXWO/I9YC14KO/F0ZSXWOI9YC14KO.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (69, 'Bottle Boogie Flute!', 'https://www.instructables.com/Bottle-Boogie-Flute/', 'https://content.instructables.com/F7P/R4U0/I9YBIT0H/F7PR4U0I9YBIT0H.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (70, 'Galaxy Scanner!  (make Planetary Pictures at Home)', 'https://www.instructables.com/Galaxy-Scanner-make-planetary-pictures-at-home/', 'https://content.instructables.com/F5O/ZE0H/I9UEA1WU/F5OZE0HI9UEA1WU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (71, 'Viscosity Tube Tumbler', 'https://www.instructables.com/Viscosity-Tube-Tumbler/', 'https://content.instructables.com/FY8/3WBR/I9LZH6TG/FY83WBRI9LZH6TG.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (72, 'Wind Tube!', 'https://www.instructables.com/Wind-Tube/', 'https://content.instructables.com/FQL/XIXK/I9JR90BI/FQLXIXKI9JR90BI.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (73, 'Glitter Roulette With Party Poppers', 'https://www.instructables.com/Glitter-Roulette-with-Party-Poppers/', 'https://content.instructables.com/FDV/6MDR/I9E1C8UW/FDV6MDRI9E1C8UW.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (74, 'Water Lava Lamp (learning Density)', 'https://www.instructables.com/Water-Lava-Lamp/', 'https://content.instructables.com/FP1/I98W/I9CLWFHM/FP1I98WI9CLWFHM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (75, 'PVC Speaker From Scratch!', 'https://www.instructables.com/PVC-Speaker-From-Scratch/', 'https://content.instructables.com/FV1/FBFZ/I9C84J63/FV1FBFZI9C84J63.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (76, 'Maggie the Simple Electromagnet!', 'https://www.instructables.com/Maggie-the-Electromagnet/', 'https://content.instructables.com/FQK/O9GZ/I9B6HD0U/FQKO9GZI9B6HD0U.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (77, 'Make a Muppet Puppet!', 'https://www.instructables.com/Make-a-Muppet-Puppet/', 'https://content.instructables.com/FGG/KXKL/I9ABB0CW/FGGKXKLI9ABB0CW.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (78, 'Water Drop Trampoline', 'https://www.instructables.com/Water-Drop-Trampoline/', 'https://content.instructables.com/FVZ/JQSS/I95GQQS8/FVZJQSSI95GQQS8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (79, 'Music You Can See', 'https://www.instructables.com/Music-You-Can-See/', 'https://content.instructables.com/F8G/JGJ4/I95GPBWC/F8GJGJ4I95GPBWC.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (80, 'Wind Turbine Game!', 'https://www.instructables.com/Wind-Turbine-Game/', 'https://content.instructables.com/FZH/IRXF/I92LTXSM/FZHIRXFI92LTXSM.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (81, 'Flower Dissection!', 'https://www.instructables.com/Flower-Dissection/', 'https://content.instructables.com/FAV/7R4G/I916FKAL/FAV7R4GI916FKAL.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (82, 'Wire Maze!', 'https://www.instructables.com/Wire-Maze/', 'https://content.instructables.com/F4F/V1YF/I8YBOJHB/F4FV1YFI8YBOJHB.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (83, 'Pinhole Eye Model', 'https://www.instructables.com/Pinhole-Eye-Model/', 'https://content.instructables.com/F0V/D219/I8UUVBMU/F0VD219I8UUVBMU.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (84, 'Light Drum!', 'https://www.instructables.com/Light-Drum/', 'https://content.instructables.com/FW6/ZHC9/I8UUV7U5/FW6ZHC9I8UUV7U5.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (85, 'Squid Dissection', 'https://www.instructables.com/Squid-Dissection/', 'https://content.instructables.com/FEU/I2IK/I8PQWTJH/FEUI2IKI8PQWTJH.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (86, 'Rubber Band Harmonica!', 'https://www.instructables.com/Rubber-Band-Harmonica/', 'https://content.instructables.com/FH8/NMX6/I8PQVS2B/FH8NMX6I8PQVS2B.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (87, 'Glove-a-Trombone!', 'https://www.instructables.com/Glove-a-Trombone/', 'https://content.instructables.com/FJ1/W7YA/I8MVZ3NL/FJ1W7YAI8MVZ3NL.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (88, 'Giant Wave Model!', 'https://www.instructables.com/Giant-Wave-Model/', 'https://content.instructables.com/F20/37DP/IGCJLUNF/F2037DPIGCJLUNF.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (89, 'Circuit Tiles!', 'https://www.instructables.com/Circuit-Tiles/', 'https://content.instructables.com/FCI/WTYJ/I8K13MM4/FCIWTYJI8K13MM4.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (90, 'Jurassic Pie!', 'https://www.instructables.com/Jurassic-Pie-aka-Volcano-Cake/', 'https://content.instructables.com/FJE/R74V/I8H69CK1/FJER74VI8H69CK1.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (91, 'Strobe Goggles: Your Ticket to Stardom!', 'https://www.instructables.com/Strobe-Goggles/', 'https://content.instructables.com/FRU/I248/I8FQRERX/FRUI248I8FQRERX.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (92, 'Elasti-Bot: the Posable Wooden Robot', 'https://www.instructables.com/Elasti-Bot-the-posable-wooden-robot/', 'https://content.instructables.com/FQZ/JC80/I8BGGZFI/FQZJC80I8BGGZFI.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (93, 'Balance Bot Buddy!', 'https://www.instructables.com/Build-a-Balancing-Bot-Buddy/', 'https://content.instructables.com/FTT/5SC2/I8BGHB11/FTT5SC2I8BGHB11.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (94, 'BoomBucket: the Boombox Bucket!', 'https://www.instructables.com/BoomBucket-the-boombox-bucket/', 'https://content.instructables.com/F1J/B78B/I3H52O7F/F1JB78BI3H52O7F.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (95, 'Scissor Lift (by Craft Sticks!)', 'https://www.instructables.com/Scissor-Lift-by-craft-sticks/', 'https://content.instructables.com/FKH/X4WQ/I3H52UP9/FKHX4WQI3H52UP9.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (96, 'Straw Propellor', 'https://www.instructables.com/Straw-Propellor/', 'https://content.instructables.com/FSB/KYIO/I3BH745F/FSBKYIOI3BH745F.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (97, 'Bite-sized Boombox', 'https://www.instructables.com/BoomBiteBox-listening-with-your-teeth/', 'https://content.instructables.com/F3S/DJR3/I3AKC21M/F3SDJR3I3AKC21M.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (98, 'Wobble Bot!', 'https://www.instructables.com/Wobble-Bot/', 'https://content.instructables.com/FE6/5T8K/I3AKBGB8/FE65T8KI3AKBGB8.jpg?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (99, 'Straw Finger', 'https://www.instructables.com/Straw-Finger/', 'https://content.instructables.com/FFI/P4IM/I395RYUI/FFIP4IMI395RYUI.png?auto=webp&crop=1.2%3A1&frame=1&width=306'),
    (100, 'Straw Flute', 'https://www.instructables.com/Straw-Flute/', 'https://content.instructables.com/F7Y/TM0F/I395RQCF/F7YTM0FI395RQCF.png?auto=webp&crop=1.2%3A1&frame=1&width=306')
)
update public.steamh_projects as projects
set
  image_urls = jsonb_build_array(source_titles.cover_url),
  external_links = jsonb_build_array(
    jsonb_build_object(
      'label', 'Activity Page',
      'url', source_titles.activity_url
    ),
    jsonb_build_object(
      'label', 'Source Collection',
      'url', 'https://www.instructables.com/100-STEAM-Projects-for-Educators/'
    )
  ),
  updated_at = now()
from source_titles
where lower(projects.title) = lower(source_titles.title);

notify pgrst, 'reload schema';
