import { NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

const SYSTEM_PROMPT = `
You are a "Historical Exam Question Retrieval Engine" for JEE Mains, JEE Advanced, and NEET.
Your task is to provide a REAL historical question from the specified exam, subject, and year.

OUTPUT FORMAT (JSON ONLY):
{
  "id": "string-unique-id",
  "exam": "JEE Mains" | "JEE Advanced" | "NEET",
  "subject": "Physics" | "Chemistry" | "Mathematics" | "Biology",
  "year": number,
  "text": "The full text of the question",
  "options": [
    { "label": "A", "text": "option text" },
    { "label": "B", "text": "option text" },
    { "label": "C", "text": "option text" },
    { "label": "D", "text": "option text" }
  ],
  "correctAnswer": "A" | "B" | "C" | "D",
  "logicContext": "A detailed step-by-step derivation or logical breakdown of how to reach the correct answer. This is used by another AI to monitor student handwriting."
}

CRITICAL:
1. The question MUST be a real question that appeared in that specific year's paper.
2. If the year is very recent (2023, 2024), ensure the question is accurate.
3. The logicContext must be extremely detailed, including any formulas or principles used.
4. Return ONLY the JSON object. No preamble or postamble.
`;

export async function POST(req: Request) {
  const apiKey = [
    process.env.GOOGLE_API_KEY,
    process.env.GOOGLE_API_KEY_QUESTIONS,
    process.env.GOOGLE_API_KEY_FALLBACK,
  ].find(k => k && k.trim().length > 0 && k.startsWith("AIza"));

  if (!apiKey) {
    return NextResponse.json({ error: "Missing Google API Key. Set GOOGLE_API_KEY in .env.local" }, { status: 500 });
  }

  try {
    const { exam, subject, year } = await req.json();

    const modelName = process.env.GEMINI_MODEL || "gemini-2.5-flash";
    const genAI = new GoogleGenerativeAI(apiKey);
    // Move systemInstruction into the prompt for maximum compatibility
    const model = genAI.getGenerativeModel({ model: modelName }, { apiVersion: "v1" });

    const combinedPrompt = `${SYSTEM_PROMPT}\n\nUSER REQUEST: Provide a real ${subject} question from the ${exam} ${year} paper.`;

    const result = await model.generateContent({
      contents: [{ role: "user", parts: [{ text: combinedPrompt }] }],
      generationConfig: { 
        temperature: 0.2, 
        maxOutputTokens: 1000
      },
    });

    const content = result.response.text();
    if (!content) {
      return NextResponse.json({ error: "No question generated by AI" }, { status: 500 });
    }

    // Clean markdown if present
    const cleanJson = content.replace(/```json/g, "").replace(/```/g, "").trim();
    
    try {
      const questionData = JSON.parse(cleanJson);
      return NextResponse.json(questionData);
    } catch {
      console.error("JSON Parse Error:", cleanJson);
      return NextResponse.json({ error: "Malformed response from AI" }, { status: 500 });
    }
  } catch (err) {
    const error = err as Error;
    console.error("Fetch Question Error:", error);
    return NextResponse.json({ error: error.message || "Internal Server Error" }, { status: 500 });
  }
}
